### ISSUE TITLE
Blank page when using gh pages

### ISSUE THREAD

**Issue by MoAbbasid** [github-education-resources/codespaces-project-template-js#136]
as the title says,
gh pages delpyed to username.github.io/repo-name, shows blank page, after following the guide exactly, it looks like after npm run deploy, the paths are not pointed correctly

**Comment by amiii123malviya** [comment]
Is this issue still active?

**Comment by MoAbbasid** [comment]
No it suddenly worked, I couldnt Identify the reason tho
